name: trackingworks
description: A new Flutter project.

# Build android app need add --no-shrink to fix image_picker in release mode
publish_to: "none"
version: 2.0.0+20

environment:
  # sdk: ">=2.16.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  attendance:
    path: features/employee/attendance
  auth:
    path: features/auth
  component:
    path: shared/component
  core:
    path: core
  dependencies:
    path: shared/dependencies
  files:
    path: features/files
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  l10n:
    path: shared/l10n
  leave:
    path: features/employee/leave
  main:
    path: features/main
  notice:
    path: features/employee/notice
  payroll:
    path: features/employee/payroll
  preferences:
    path: shared/preferences
  profile:
    path: features/employee/profile
  resign:
    path: features/employee/resign
  settings:
    path: features/settings
  uuid: ^4.5.1
  geolocator: ^14.0.2
# dependency_overrides:
#   platform: ^3.1.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_abb.png"

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/images/
    - assets/images/marker/
    - assets/images/flags/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Icons_new
      fonts:
        - asset: assets/fonts/Icons_new.ttf
    - family: TicketingIcons
      fonts:
        - asset: assets/fonts/TicketingIcons.ttf
    - family: AppIcon2
      fonts:
        - asset: assets/fonts/AppIcons2.ttf
