name: notice
description: A new Flutter package project.
version: 0.0.2
homepage: "https://kodingworks.io/"

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^30.1.40
  shared_preferences: ^2.5.3
  component:
    path: ../../../shared/component
  core:
    path: ../../../core
  dependencies:
    path: ../../../shared/dependencies
  l10n:
    path: ../../../shared/l10n
  preferences:
    path: ../../../shared/preferences
  files:
    path: ../../files

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
