name: dependencies
description: A new Flutter package project.
version: 0.0.2
homepage: "https://kodingworks.io/"

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  flutter_html: ^3.0.0
  formz: ^0.4.0-nullsafety.0
  get_it: ^7.2.0
  hive: ^2.0.5
  image_picker: ^1.1.2
  path_provider: ^2.0.8
  file_picker: ^10.2.0
  rxdart: ^0.27.3
  open_file_safe_plus: ^0.0.6
  pdf: ^3.7.1
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_crashlytics: ^4.3.9
  firebase_performance: ^0.10.1+9
  firebase_analytics: ^11.5.2
  geolocator: ^9.0.2
  firebase_remote_config: ^5.4.7
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.2
  shimmer: ^2.0.0
  intl: ^0.20.2
  google_maps_flutter: ^2.12.3
  timeline_tile: ^2.0.0
  permission_handler: ^10.2.0
  flutter_downloader: ^1.12.0
  flutter_local_notifications: ^19.3.1
  android_alarm_manager_plus: ^4.0.7
  internet_connection_checker: ^0.0.1+3
  sentry_flutter: ^9.4.1
  workmanager: ^0.8.0
  shared_preferences: ^2.5.3
  slide_to_act: ^2.0.2
  flutter_keyboard_visibility: ^6.0.0
  page_transition: ^2.0.5
  flutter_linkify: ^5.0.2
  syncfusion_flutter_datepicker: ^30.1.40
  flutter_typeahead: ^5.2.0
  syncfusion_flutter_pdfviewer: ^30.1.40
  dotted_border: ^2.0.0+1
  autocomplete_textfield: ^2.0.0
  percent_indicator: ^3.4.0
  dropdown_button2: ^1.4.0
  flutter_device_id:
    path: ../flutter_device_id
  native_camera:
    path: ../native_camera
  background_locator:
    path: ../background_locator

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
